// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHpd745cJzVD1_WVWqZi0MTA8PP79O3Lk',
    appId: '1:823801819905:web:fec89d4ce0706e33786100',
    messagingSenderId: '823801819905',
    projectId: 'streetfeast-b38c0',
    authDomain: 'streetfeast-b38c0.firebaseapp.com',
    storageBucket: 'streetfeast-b38c0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABozupTFrsvGmPplOZyrFb56owBbZ8ZRY',
    appId: '1:823801819905:android:774d674ed1e82ea1786100',
    messagingSenderId: '823801819905',
    projectId: 'streetfeast-b38c0',
    storageBucket: 'streetfeast-b38c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUdZBrVfeBNvc5qFmnvy9PT3OHvnQAOsw',
    appId: '1:823801819905:ios:4f12d4a355a51b59786100',
    messagingSenderId: '823801819905',
    projectId: 'streetfeast-b38c0',
    storageBucket: 'streetfeast-b38c0.firebasestorage.app',
    iosBundleId: 'com.example.streetfeastApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUdZBrVfeBNvc5qFmnvy9PT3OHvnQAOsw',
    appId: '1:823801819905:ios:4f12d4a355a51b59786100',
    messagingSenderId: '823801819905',
    projectId: 'streetfeast-b38c0',
    storageBucket: 'streetfeast-b38c0.firebasestorage.app',
    iosBundleId: 'com.example.streetfeastApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHpd745cJzVD1_WVWqZi0MTA8PP79O3Lk',
    appId: '1:823801819905:web:b91ea5fbae6c8027786100',
    messagingSenderId: '823801819905',
    projectId: 'streetfeast-b38c0',
    authDomain: 'streetfeast-b38c0.firebaseapp.com',
    storageBucket: 'streetfeast-b38c0.firebasestorage.app',
  );
}
